export const defaultTenantTheme = {
    light: {
        '--color-bg': '#f3f5fb',
        '--color-surface': '#ffffff',
        '--color-surface-alt': '#f7f9ff',
        '--color-sidebar': '#eef2fb',
        '--color-text': '#121a2b',
        '--color-muted': '#5b6882',
        '--color-border': '#d9e0ef',
        '--color-primary': '#1676ff',
        '--color-secondary': '#14b890',
        '--color-accent': '#ff9f1c',
    },
    dark: {
        '--color-bg': '#0a101a',
        '--color-surface': '#121c2a',
        '--color-surface-alt': '#172334',
        '--color-sidebar': '#0d1826',
        '--color-text': '#e8eef9',
        '--color-muted': '#97a7c1',
        '--color-border': '#243447',
        '--color-primary': '#67a8ff',
        '--color-secondary': '#3bd2af',
        '--color-accent': '#ffb347',
    },
} as const;
